### ISSUE TITLE
Compare different coupling strategies

### ISSUE THREAD

**Issue by zachbe** [zbelateche/digial-ising#16]
The AND-gate-based phase locking used in `shorted_cell.v`  forces the vertical and horizontal oscillators to have the exact same phase, unlike the strong resistive phase locking used in Lo. et al. However, it also prevents the DIMPLE solver from setting different halves of the coupling matrix to different weights, which reduces the overall weight resolution.

If that doesn't work well, it should be possible to reduce that to a single coupled cell per coupling, and eliminate the shorted cells from the design. However, this disrupts the regular recursive structure of the core matrix.

**Comment by zbelateche** [comment]
Looks like there is a matrix structure that supports single-cell coupling well!

<img src="https://github.com/zbelateche/digial-ising/assets/11079820/e4f94b94-ba38-4b02-9619-381bb18492c0" alt="drawing" width="500"/>

**Comment by zachbe** [comment]
Done with PR #22
